"""
pipeline/analysis/counter_evidence.py — Counter Evidence Search (T3.6)

Uses Groq (opposite-provider to Gemini which generated insights) to scan the
corpus for quotes that explicitly contradict the generated insights.
Contradictions are persisted to a dead-letter/counter-evidence log and appended
to the final report for honesty.
"""

from __future__ import annotations

import json
import logging
from typing import Any

from pipeline.analysis.schemas import CounterEvidenceResponse, current_raw_text
from pipeline.common import (
    ANALYSIS_DIR,
    DATA_DIR,
    iter_jsonl,
    setup_logging,
)
from pipeline.llm import Provider, get_gateway

logger = logging.getLogger(__name__)

CORPUS_PATH = DATA_DIR / "clean" / "corpus.jsonl"
INSIGHTS_PATH = ANALYSIS_DIR / "insights.json"


def build_prompt_with_insights(insights_summary: str):
    def prompt_builder(item: dict[str, Any]) -> tuple[str, str]:
        # Inject for validation (re-using the current_raw_text trick just in case we add a validator)
        text_raw = item.get("text_raw", "")
        current_raw_text.set(text_raw)
        
        system_msg = (
            "You are a critical auditor reviewing an e-commerce review for Blinkit.\n"
            "Below are the primary insights generated by another AI model.\n"
            f"{insights_summary}\n\n"
            "Your job is to find COUNTER-EVIDENCE. Read the provided user review. "
            "Does it EXPLICITLY contradict any of the insights above?\n"
            "If yes, return the 'insight_title' it contradicts, the 'contradicting_quote' (MUST BE AN EXACT SUBSTRING of the review), "
            "and a brief 'explanation'.\n"
            "If it does not contradict any insights, return an empty 'contradictions' list.\n"
            "DO NOT force a contradiction. Only return one if it is clearly evident."
        )
        
        full_text = f"Context: {item.get('context', '')}\nReview: {text_raw}"
        
        return system_msg, full_text
        
    return prompt_builder


def process() -> None:
    setup_logging()
    logger.info("Starting T3.6 Counter-Evidence Pass...")

    if not INSIGHTS_PATH.exists() or not CORPUS_PATH.exists():
        logger.warning("Insights or Corpus file missing. Cannot run counter-evidence.")
        return

    # Load insights to summarize them for Groq
    with INSIGHTS_PATH.open("r", encoding="utf-8") as f:
        insights_data = json.load(f)
        
    insights = insights_data.get("insights", [])
    if not insights:
        logger.info("No insights found.")
        return
        
    summary_lines = []
    for ins in insights:
        summary_lines.append(f"Title: {ins['insight_title']}\nSummary: {ins['synthesis_narrative']}")
        
    insights_summary = "\n\n".join(summary_lines)

    items = list(iter_jsonl(CORPUS_PATH))
    if not items:
        logger.info("Corpus is empty.")
        return

    gateway = get_gateway()
    
    # We use Groq (opposite provider) to batch scan the entire corpus for contradictions
    results = gateway.batch_process(
        items=items,
        item_id_key="id",
        prompt_builder=build_prompt_with_insights(insights_summary),
        schema=CounterEvidenceResponse,
        provider=Provider.GROQ,
        batch_name="counter_evidence",
        temperature=0.1
    )
    
    # Check how many contradictions were found
    total_contradictions = 0
    for item_dict, resp_obj, _ in results:
        total_contradictions += len(resp_obj.contradictions)
        
    logger.info(f"Counter-evidence pass complete. Found {total_contradictions} contradicting quotes.")


if __name__ == "__main__":
    process()
